<<<<<<< HEAD
- id: '1630553122387'
  alias: Precio Bitcoin
  description: 'Obtener precio del Bitcoin'
  trigger:
  - platform: event
    event_type: rhasspy_Bitcoin
  condition: []
  action:
  - service: rest_command.bitcoin
  mode: single

- id: '1630992001394'
  alias: Creador
  description: 'Decir quien es el creador'
  trigger:
  - platform: event
    event_type: rhasspy_Creador
  condition: []
  action:
  - service: rest_command.creador
=======
- id: '1630991114323'
  alias: Obtener temperatura
  description: ''
  trigger:
  - platform: event
    event_type: rhasspy_Temperatura
  condition: []
  action:
  - service: rest_command.temperatura
>>>>>>> SessionMaterialWeather
  mode: single
