- id: '1630991114323'
  alias: Obtener temperatura
  description: ''
  trigger:
  - platform: event
    event_type: rhasspy_Temperatura
  condition: []
  action:
  - service: rest_command.temperatura
  mode: single
