
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

rest_command:
  creador:
    url: http://192.168.15.51:12101/api/text-to-speech?play=true
    method: POST
    headers:
      accept: "audio/wav"
      content-type: "text/plain"
    payload: "Mi creador se llama {{ state_attr('person.yael','friendly_name') }}"

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
