
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

rest_command:
  bitcoin:
    url: http://192.168.15.51:12101/api/text-to-speech?play=true
    method: POST
    headers:
      accept: "audio/wav"
      content-type: "text/plain"
    payload: "Un bitcoin vale {{ states('sensor.exchange_rate_1_btc') }} dólares"

  temperatura:
    url: http://192.168.15.51:12101/api/text-to-speech?play=true
    method: POST
    headers:
      accept: "audio/wav"
      content-type: "text/plain"
    payload: "La temperatura actual es {{ state_attr('weather.casa','temperature') }} grados centigrados"

  creador:
    url: http://192.168.15.51:12101/api/text-to-speech?play=true
    method: POST
    headers:
      accept: "audio/wav"
      content-type: "text/plain"
    payload: "Mi creador se llama {{ state_attr('person.yael','friendly_name') }}"


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
